liip:
    resource: '@PiedWebCMSBundle/Resources/config/routes/liip_imagine.yaml'

user:
    resource: '@PiedWebCMSBundle/Resources/config/routes/user.yaml'

admin:
    resource: '@PiedWebCMSBundle/Resources/config/routes/admin.yaml'

piedweb_cms_homepage:
    path:     /
    controller: PiedWeb\CMSBundle\Controller\PageController::show
    methods:    [GET, HEAD]

media:
    resource: '@PiedWebCMSBundle/Resources/config/routes/media.yaml'

localized_page:
    name_prefix: localized_
    resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'
    trailing_slash_on_root: true

page:
    resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'
