import:
    resource: @PiedWebCMSBundle/Resources/config/routes/page.yaml

import:
    resource: @PiedWebCMSBundle/Resources/config/routes/contact.yaml

import:
    resource: @PiedWebCMSBundle/Resources/config/routes/footer.yaml



import:
    resource: @PiedWebCMSBundle/Resources/config/routes/fos_user.yaml

import:
    resource: @PiedWebCMSBundle/Resources/config/routes/sonata_admin.yaml
