liip:
    resource: '@PiedWebCMSBundle/Resources/config/routes/liip_imagine.yaml'

contact:
    resource: '@PiedWebCMSBundle/Resources/config/routes/contact.yaml'

footer:
    resource: '@PiedWebCMSBundle/Resources/config/routes/footer.yaml'

user:
    resource: '@PiedWebCMSBundle/Resources/config/routes/user.yaml'

admin:
    resource: '@PiedWebCMSBundle/Resources/config/routes/admin.yaml'

piedweb_cms_homepage:
    path:     /
    controller: PiedWeb\CMSBundle\Controller\PageController::show
    methods:    [GET, HEAD]

page:
    resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'
    prefix: /{_locale}
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'
    trailing_slash_on_root: true # it's ever the default value

#_errors:
#    resource: '@TwigBundle/Resources/config/routing/errors.xml'
#    prefix:   /_error
