
piedweb_cms_page:
    path:     /{slug}
    controller: PiedWeb\CMSBundle\Controller\PageController::show
    methods:    [GET, HEAD]
    requirements:
        slug: '[a-zA-Z1-9\-_]*'

piedweb_cms_footer:
    path:     /~footer
    controller: PiedWeb\CMSBundle\Controller\PageController::footer
    methods:    [POST]
