framework:
    translator: { fallbacks: ["%locale%"] }
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~
        cookie_lifetime: 0
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    php_errors:
        log: true

    default_locale: fr

    cache:


    templating:
        engines: ['twig', 'php']
