sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    title: 'Admin'
    title_logo: assets/logo_title.png
    dashboard:
        blocks:
            #- { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.page:
                label: Pages #admin.label.content
                label_catalogue: Pages #admin.label.content
                items:
                    - piedweb.admin.page
                    - piedweb.admin.media

            app.admin.group.static:
                label: Mettre en ligne
                label_catalogue: Mettre en ligne
                icon:            '<i class="fa fa-bolt"></i>'
                items:
                    - route:        piedweb_cms_page_scanner
                      label:        Vérifier le contenu
                    - route:        piedweb_static_generate
                      label:        Actualiser

            app.admin.group.setting:
                label: Paramètres #admin.label.user
                label_catalogue: Paramètres #admin.label.user
                icon:            '<i class="fa fa-wrench"></i>'
                items:
                    - piedweb.admin.user
                    - route:        piedweb_cms_template_editor_list
                      label:        Thème
    options:
        lock_protection: true
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css


sonata_doctrine_orm_admin:
    templates:
        form:
            - "@PiedWebCMS/admin/sd_form_admin_fields.html.twig"

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata_translation.block.locale_switcher: ~
        sonata.admin.block.search_result:
            contexts:   [admin]
