sonata_admin:
    title: 'Admin'
    title_logo: assets/logo_title.png
    dashboard:
        blocks:
            #- { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.page:
                label: Pages #admin.label.content
                label_catalogue: Pages #admin.label.content
                items:
                    - piedweb.admin.page
                    - piedweb.admin.media

            app.admin.group.user:
                label: Utilisateurs #admin.label.user
                label_catalogue: Utilisateurs #admin.label.user
                items:
                    - piedweb.admin.user
    options:
        lock_protection: true
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css


sonata_translation:
    locales: [fr, en] # TODO can't get array from parameters
    default_locale: '%locale%'
    gedmo:
        enabled: true

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata_translation.block.locale_switcher: ~
        sonata.admin.block.search_result:
            contexts:   [admin]
