twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../vendor/sonata-project/admin-bundle/src/Resources/views": SonataAdmin
        #"%kernel.root_dir%/../templates": App
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
    globals:
        img_dir:
            url: "/%img_dir%"
        logo_alt: "%app_name%"
        contact_email: "%app_contact_email%"
