vich_uploader:
    db_driver: orm

    mappings:
        image_image:
            uri_prefix: /images/
            upload_destination: '%img_dir_absolute%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}

