vich_uploader:
    db_driver: orm

    mappings:
        media_media:
            #uri_prefix:
            upload_destination: '%app.media_dir_absolute%'
            namer:
                service: PiedWeb\CMSBundle\Service\VichUploadPropertyNamer #Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}
            directory_namer:
                service: vich_uploader.namer_directory_current_date_time
                options: {date_time_format: 'Y'}
