services:


# --------
# Me
# --------

    PiedWeb\CMSBundle\PiedWebCMSBundle: ~

    PiedWeb\CMSBundle\:
        autowire: true
        resource: '../../../src/*'
        exclude: '../../../src/{Repository,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    PiedWeb\CMSBundle\Controller\:
        autowire: true
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    PiedWeb\CMSBundle\EventListener\MediaListener:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $em: '@doctrine.orm.entity_manager'
            $cacheManager: '@liip_imagine.cache.manager'
            $dataManager: '@liip_imagine.data.manager'
            $filterManager: '@liip_imagine.filter.manager'
        tags:
            - { name: kernel.event_listener, event: vich_uploader.pre_upload }
            - { name: kernel.event_listener, event: vich_uploader.post_upload }
            #- { name: doctrine.orm.entity_listener, entity: PiedWeb\CMSBundle\Entity\Image, event: prePersist }

    PiedWeb\CMSBundle\EventListener\PageListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%app.entity_page%', event: preRemove }

    piedweb.feed.dumper:
        class: PiedWeb\CMSBundle\Service\FeedDumpService
        arguments: [ "@doctrine.orm.entity_manager", "@twig", "@piedweb.page_canonical", "%app.dir%", '%app.entity_page%']

    # Required for sonata Translation
    stof_doctrine_extensions.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ true ]]

    Gedmo\Translatable\TranslatableListener:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ true ]]
            #- [ setTranslatableLocale, [ "@=service('request_stack').getCurrentRequest().getLocale()" ]]

    PiedWeb\CMSBundle\Twig\AppExtension:
        tags:
            - 'twig.extension'
            #- { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ "@piedweb.page_canonical"]

    piedweb.page_canonical:
        class: PiedWeb\CMSBundle\Service\PageCanonicalService
        arguments: [ "@request_stack", "@router", '%app.default_locale_without_prefix%', '%locale%']
        public: true

    PiedWeb\CMSBundle\Service\PageCanonicalService:
        alias: piedweb.page_canonical
        public: true

# --------
# Repository
# --------

    PiedWeb\CMSBundle\Repository\PageRepository:
        arguments: ['@doctrine', '%app.entity_page%']
        tags:
            - { name: doctrine.repository_service }

    PiedWeb\CMSBundle\Repository\MediaRepository:
        arguments: ['@doctrine', '%app.entity_media%']
        tags:
            - { name: doctrine.repository_service }

# --------
# Admin
# --------

    piedweb.admin.page:
        class: PiedWeb\CMSBundle\Admin\PageAdmin
        arguments: [~, '%app.entity_page%', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.page }
        calls:
            - [ setFeedDumper, [ '@piedweb.feed.dumper' ] ]
            - [ setLiipImage, [ '@liip_imagine.cache.manager' ] ]
            - [ setTemplate, [list, '@@PiedWebCMS/admin/media_mosaic.html.twig']]
            - [ setDefaultLocale, [ '%locale%' ] ]
        public: true

    piedweb.admin.media:
        class: PiedWeb\CMSBundle\Admin\MediaAdmin
        arguments: [~, '%app.entity_media%', ~]
        calls:
            - [ setLiipImage, [ '@liip_imagine.cache.manager' ] ]
            - [ setTemplate, [list, '@@PiedWebCMS/admin/media_mosaic.html.twig']]
            - [ setTemplate, [outer_list_rows_mosaic, '@@PiedWebCMS/admin/media_mosaic_body.html.twig']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.media }

    piedweb.admin.pagehasmedia:
        class: PiedWeb\CMSBundle\Admin\PageHasMedia
        arguments: [~, '%app.entity_pagehasmedia%', ~]
        calls:
            - [ setLiipImage, [ '@liip_imagine.cache.manager' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm }

    piedweb.admin.user:
        class: PiedWeb\CMSBundle\Admin\UserAdmin
        arguments: [~, '%app.entity_user%', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.user }
        public: true

# --------
# TWIG extension
# --------

    piedweb.app.twig.extension.loader:
        class:        Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }

    dpolac.twig_lambda.extension:
        class: DPolac\TwigLambda\LambdaExtension
        tags: [ { name: twig.extension } ]

    piedweb.twig.extension.php_function:
        class: Umpirsky\Twig\Extension\PhpFunctionExtension
        public: false
        tags:
            - { name: twig.extension }
        calls:
            - [allowFunction, ["str_rot13"]]

    piedweb.twig.extension.render_attributes:
        class: PiedWeb\RenderAttributes\TwigExtension
        public: false
        tags:
            - { name: twig.extension }

    piedweb.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }


    piedweb_cms.mailer:
        class: PiedWeb\CMSBundle\Mailer\Mailer
        arguments: ['@mailer', '@router', '@templating', '%app.email_sender%', '%app.email_sender_name%']

    PiedWeb\CMSBundle\Mailer\Mailer:
        alias: piedweb_cms.mailer
# --------
# Extending other bundles
# --------

    imagine.cache.resolver.piedweb:
        class: PiedWeb\CMSBundle\Service\ImagineWebCacheResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%app.dir%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: piedweb_relativeimgcache }

    vich_uploader.piedweb.namer_property:
        class: PiedWeb\CMSBundle\Service\VichUploadPropertyNamer
        public: true

    PiedWeb\CMSBundle\Service\VichUploadPropertyNamer:
        alias: vich_uploader.piedweb.namer_property
        public: true
